import './globals.css'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="p-5">
        <header className="flex border-b-2 border-b-slate-500">
          <div className="pe-5 py-2 hover:text-red-400">
            <Link href={'/'}>Home </Link>
          </div>
          <div className="pe-5 py-2">
            <Link href={'/articles'}>Articles </Link>
          </div>
        </header>

        {children}
      </body>
    </html>
  )
}
